### PR TITLE
feat: support full project CRUD

### PR DESCRIPTION
**Pull request by bitpshr**
This pull request updates the API transport by adding support for project creation, updating, deletion, archiving, and unarchiving.

Requires https://github.com/goabstract/projects/pull/3841
References #180

### CODE REVIEW

**Comment by tommoor** [comment]
Unfortunately we can't enable project creation via the SDK until the underlying repository is setup entirely server-side, currently the API endpoint relies on the fact that the desktop client will create the repository with a `PROJECT_CREATED` commit and push that to the server.

I think we'll need a new API version that enables gitnode to perform this operation, rather than the client, and then use that API version here before it's mergeable.

**Comment by bitpshr** [comment]
Ah, thanks for this @tommoor. I will try to get the gitnode stuff in place.

**Comment by tommoor** [comment]
Removing review request until backend is ready.

**Comment by bitpshr** [comment]
Ready for another pass now that the backend changes are live and the API version has been bumped @tommoor. Thanks in advance!

**Pull request merged**
